# Generated by Django 2.1.5 on 2019-02-13 05:27

from django.conf import settings
from django.db import migrations, models
import tweets.models
import tweets.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=120, validators=[tweets.validators.validate_content])),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.SET(tweets.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
